apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: purser
resources:
  - namespace.yaml
  - configmap-policy.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
