{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "purser.fullname" . }}
  labels:
    {{- include "purser.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "purser.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: core
{{- end }}
