{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "purser.authSecretName" . }}
  labels:
    {{- include "purser.labels" . | nindent 4 }}
  annotations:
    # keep the key stable across upgrades (don't regenerate)
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ include "purser.apiKey" . | quote }}
{{- end }}
